# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
deploymentLabel: loans

replicaCount: 1

image:
  repository: saipavan9594/section13-loans
  tag: latest

containerPort: 8082

service:
  type: 
  port: 8082
  targetPort: 8082

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false